### ISSUE TITLE
add MIT License

### ISSUE THREAD

**Issue by dothibich2001** [PhamTienDat42/btl-react#6]
thiếu MIT License

**Comment by PhamTienDat42** [comment]
can u give me one?

**Comment by PhamTienDat42** [comment]
i have just been merge your pull request of MIT license, many thanks!
![gitLecenseMitreacrt](https://github.com/PhamTienDat42/btl-react/assets/117574501/28ea1693-6834-4a2b-b86a-b30e1f1a0829)
